web/router.ex
defmodule Werewolf.Router do
  use Werewolf.Web, :router

  pipeline :browser do
    plug :accepts, ["html"]
    plug :fetch_session
    plug :fetch_flash
    plug :protect_from_forgery
    plug :put_secure_browser_headers
    plug Werewolf.Plug.CurrentUser
  end

  pipeline :api do
    plug :accepts, ["json"]
  end

  scope "/", Werewolf do
    pipe_through :browser # Use the default browser stack


    get "/", PageController, :index
    resources "/games", GameController
    resources "/users", UserController
    get "/login", SessionController, :new
    post "/login", SessionController, :create 
    get "/logout", SessionController, :delete
    resources "/new-game", GameCreateController, only: [:create]
    resources "/join", GameJoinController, only: [:create]
  end

  # Other scopes may use custom stacks.
  # scope "/api", Werewolf do
  #   pipe_through :api
  # end
end

web/templates/page/index.html.eex
<div class="row marketing">
  <div class="col-lg-6">
    <h4>Create a game</h4>
    <%= form_for @changeset, game_create_path(@conn, :create), fn _ -> %>
    <div class="form-group">
      <%= submit "Create", class: "btn btn-primary" %>
    </div>
    <% end %>
  </div>

  <div class="col-lg-6">
    <%= form_for @changeset, game_join_path(@conn, :create), fn f -> %>
    <div class="form-group">
      <%= label f, :slug, class: "control-label" do %>
        Game ID
      <% end %>
      <%= text_input f, :slug, class: "form-control" %>
      <%= error_tag f, :slug %>
    </div>
    <div class="form-group">
      <%= submit "Join Game", class: "btn btn-primary" %>
    </div>
    <% end %>
  </div>
</div>